require("profiles.mrcatnerd.plugins.lsp.filetypes.all")
require("profiles.mrcatnerd.plugins.lsp.filetypes.rust")
require("profiles.mrcatnerd.plugins.lsp.filetypes.python")
require("profiles.mrcatnerd.plugins.lsp.filetypes.lua")
require("profiles.mrcatnerd.plugins.lsp.filetypes.c")
require("profiles.mrcatnerd.plugins.lsp.filetypes.cpp")
